// D-ONE Motors — Full Inventory (34 vehicles)
// Auto-generated from existing App.jsx data + scraped listing details

export const inventory = [
  // ─────────────────────────────────────────────
  // EXISTING 10 CARS (from App.jsx)
  // ─────────────────────────────────────────────
  {
    id: 'range-rover-p530-caraway',
    brand: 'Range Rover',
    model: 'P530 Autobiography LWB',
    year: 2026,
    price: 207000,
    tag: 'New',
    mileage: '0 km',
    color: 'Santorini Black',
    interior: 'Caraway',
    engine: '4.4L V8 Twin-Turbo',
    power: '530 HP',
    transmission: 'Automatic',
    fuel: 'Petrol',
    drivetrain: 'AWD',
    image: '/cars/range-rover-p530-caraway/01.jpg',
    gallery: Array.from({length: 10}, (_, i) => `/cars/range-rover-p530-caraway/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 4.6s', topSpeed: '250 km/h', fuelConsumption: '12-13 L/100km' },
    highlights: ['V8 Twin-Turbo', '530 HP', 'Long Wheelbase', 'Autobiography'],
    description: 'The Range Rover P530 Autobiography LWB is a premium long-wheelbase SUV combining supreme comfort, powerful performance, and refined design. Santorini Black exterior with Caraway leather interior delivers a luxurious, contemporary look. Full-time AWD ensures confident handling in any road or weather condition.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'mercedes-g450d',
    brand: 'Mercedes-Benz',
    model: 'G 450 d',
    year: 2026,
    price: 162000,
    tag: 'New',
    mileage: '10 km',
    color: 'Selenite Grey',
    interior: 'Beige',
    engine: '3.0L R6 Turbodiesel',
    power: '367 HP',
    transmission: '9G-TRONIC',
    fuel: 'Diesel',
    drivetrain: '4MATIC AWD',
    image: '/cars/mercedes-g450d/01.jpg',
    gallery: Array.from({length: 7}, (_, i) => `/cars/mercedes-g450d/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 5.6s', topSpeed: '210 km/h', fuelConsumption: '9-10 L/100km' },
    highlights: ['Turbodiesel', '367 HP', 'G-Class', '4MATIC'],
    description: 'The legendary G-Class in its modern, efficient diesel form. Body-on-frame construction, permanent 4MATIC AWD, and three differential locks make it a true off-roader. The premium interior ensures the highest level of daily comfort and luxury.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'lexus-lx700h-luxury',
    brand: 'Lexus',
    model: 'LX 700h Luxury 7-Seat',
    year: 2026,
    price: 152000,
    tag: 'New',
    mileage: '0 km',
    color: 'Sonic Titanium',
    interior: 'Black',
    engine: '3.5L V6 Hybrid',
    power: '457 HP',
    transmission: 'Automatic',
    fuel: 'Hybrid (Petrol + Electric)',
    drivetrain: '4WD',
    image: '/cars/lexus-lx700h-luxury/01.jpg',
    gallery: Array.from({length: 9}, (_, i) => `/cars/lexus-lx700h-luxury/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 6.0s', topSpeed: '210 km/h', fuelConsumption: '9-10 L/100km' },
    highlights: ['V6 Hybrid', '457 HP', '7-Seat', 'Luxury'],
    description: 'The Lexus LX 700h Luxury is a premium SUV featuring advanced hybrid technology, a spacious 7-seat cabin, and top-tier safety and luxury. Sonic Titanium exterior with Black interior delivers a refined, modern look. The hybrid system improves fuel efficiency while 4WD ensures reliable handling in all conditions.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'range-rover-p530-deep-garnet',
    brand: 'Range Rover',
    model: 'P530 Autobiography LWB',
    year: 2026,
    price: 207000,
    tag: 'New',
    mileage: '0 km',
    color: 'Santorini Black',
    interior: 'Deep Garnet',
    engine: '4.4L V8 Twin-Turbo',
    power: '530 HP',
    transmission: 'Automatic',
    fuel: 'Petrol',
    drivetrain: 'AWD',
    image: '/cars/range-rover-p530-deep-garnet/01.jpg',
    gallery: Array.from({length: 6}, (_, i) => `/cars/range-rover-p530-deep-garnet/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 4.6s', topSpeed: '250 km/h', fuelConsumption: '12-13 L/100km' },
    highlights: ['V8 Twin-Turbo', '530 HP', 'Long Wheelbase', 'Deep Garnet Interior'],
    description: 'The Range Rover P530 Autobiography LWB featuring the striking Deep Garnet interior on Santorini Black. A premium long-wheelbase SUV combining supreme comfort, a powerful V8, and refined design. Full-time AWD with maximum comfort, safety, and advanced technology throughout.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'genesis-gv80-black-edition',
    brand: 'Genesis',
    model: 'GV80 2.5T Black Edition',
    year: 2026,
    price: 72500,
    tag: 'New',
    mileage: '0 km',
    color: 'Black',
    interior: 'Black',
    engine: '2.5L Turbo Hybrid',
    power: '304 HP',
    transmission: 'Automatic',
    fuel: 'Hybrid (Petrol + Electric)',
    drivetrain: 'AWD',
    image: '/cars/genesis-gv80-black-edition/01.jpg',
    gallery: Array.from({length: 10}, (_, i) => `/cars/genesis-gv80-black-edition/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 7.0s', topSpeed: '230 km/h', fuelConsumption: '7-8 L/100km' },
    highlights: ['Turbo Hybrid', 'Black Edition', 'AWD', 'Premium SUV'],
    description: 'The Genesis GV80 2.5T Black Edition Hybrid is a premium SUV combining advanced hybrid technology, supreme comfort, and striking all-black design. The hybrid system reduces fuel consumption and delivers smooth acceleration, while AWD ensures reliable handling in any conditions. Black Edition trim provides maximum luxury, safety, and cutting-edge technology.',
    category: 'suv',
    featured: true,
  },
  {
    id: 'mercedes-glc300-amg-line',
    brand: 'Mercedes-Benz',
    model: 'GLC 300 4MATIC AMG Line',
    year: 2026,
    price: 72000,
    tag: 'New',
    mileage: '0 km',
    color: 'Obsidian Black Metallic',
    interior: 'Neva Grey / Black',
    engine: '2.0L Turbo + 48V Mild Hybrid',
    power: '258 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC AWD',
    image: '/cars/mercedes-glc300-amg-line/01.jpg',
    gallery: Array.from({length: 8}, (_, i) => `/cars/mercedes-glc300-amg-line/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 6.2s', topSpeed: '240 km/h', fuelConsumption: '7.5-8.5 L/100km' },
    highlights: ['AMG Line', '258 HP', '4MATIC', 'Mild Hybrid'],
    description: 'The Mercedes-Benz GLC 300 4MATIC AMG Line combines sporty styling with daily comfort. The powerful 2.0L turbo engine with 48V Mild Hybrid provides extra dynamics during acceleration and improves fuel efficiency. AMG Line package adds sport bumpers, sport steering, wider wheels, and premium MBUX multimedia system.',
    category: 'suv',
    featured: true,
  },
  {
    id: 'mercedes-e300-amg-line',
    brand: 'Mercedes-Benz',
    model: 'E 300 AMG Line',
    year: 2026,
    price: 67000,
    tag: 'New',
    mileage: '0 km',
    color: 'Alpine Grey',
    interior: 'Brown',
    engine: '2.0L Turbo + 48V Mild Hybrid',
    power: '258 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: 'RWD',
    image: '/cars/mercedes-e300-amg-line/01.jpg',
    gallery: Array.from({length: 8}, (_, i) => `/cars/mercedes-e300-amg-line/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 6.1s', topSpeed: '250 km/h', fuelConsumption: '7-8 L/100km' },
    highlights: ['AMG Line', '258 HP', 'E-Class', 'Mild Hybrid'],
    description: 'The Mercedes-Benz E 300 AMG Line is the perfect blend of business-class comfort and sporty spirit. The AMG Line design package gives the car an aggressive, modern look, while Alpine Grey exterior with Brown leather interior emphasizes premium taste and sophistication. Mild Hybrid technology ensures fuel efficiency and smooth driving.',
    category: 'sedan',
    featured: true,
  },
  {
    id: 'genesis-g80-full-option',
    brand: 'Genesis',
    model: 'G80 4WD Full Option',
    year: 2025,
    price: 66000,
    tag: 'New',
    mileage: '0 km',
    color: 'Brooklyn Brown',
    interior: 'Ecru Camel',
    engine: '2.5L Turbo Hybrid',
    power: '304 HP',
    transmission: 'Automatic',
    fuel: 'Hybrid (Petrol + Electric)',
    drivetrain: 'AWD',
    image: '/cars/genesis-g80-full-option/01.jpg',
    gallery: Array.from({length: 10}, (_, i) => `/cars/genesis-g80-full-option/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 6.9s', topSpeed: '240 km/h', fuelConsumption: '7-8 L/100km' },
    highlights: ['Full Option', 'AWD', 'Turbo Hybrid', 'Business Sedan'],
    description: 'The Genesis G80 4WD Full Option is a premium business sedan combining modern hybrid technology, supreme comfort, and refined design. Brooklyn Brown exterior with Ecru Camel mono-tone interior delivers a luxurious, contemporary look. The hybrid system improves fuel efficiency while AWD ensures confident handling in all conditions.',
    category: 'sedan',
    featured: true,
  },
  {
    id: 'hyundai-palisade-calligraphy',
    brand: 'Hyundai',
    model: 'Palisade 2.5T Calligraphy 9-Seat',
    year: 2025,
    price: 53000,
    tag: 'New',
    mileage: '60 km',
    color: 'Black',
    interior: 'Black',
    engine: '2.5L Turbo',
    power: '281 HP',
    transmission: '8-Speed Automatic',
    fuel: 'Petrol',
    drivetrain: '4WD',
    image: '/cars/hyundai-palisade-calligraphy/01.jpg',
    gallery: Array.from({length: 6}, (_, i) => `/cars/hyundai-palisade-calligraphy/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 8.0s', topSpeed: '210 km/h', fuelConsumption: '9-11 L/100km' },
    highlights: ['Calligraphy', '9-Seat', '4WD', '2.5T'],
    description: 'The Hyundai Palisade Calligraphy is the ideal premium SUV for families and business. Black-on-Black combination gives the car a serious, luxurious look. With only 60 km on the odometer, this is practically a new vehicle. Spacious cabin, 9-seat configuration, and 4WD system make it a comfortable and reliable choice in any conditions.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'genesis-electrified-g80',
    brand: 'Genesis',
    model: 'Electrified G80 e-AWD',
    year: 2023,
    price: 40000,
    tag: 'Pre-Owned',
    mileage: '49,100 km',
    color: 'Vik Black',
    interior: 'Ecru Camel',
    engine: 'Dual Electric Motors',
    power: '365 HP',
    transmission: 'Single-Speed',
    fuel: 'Electric',
    drivetrain: 'e-AWD',
    image: '/cars/genesis-electrified-g80/01.jpg',
    gallery: Array.from({length: 7}, (_, i) => `/cars/genesis-electrified-g80/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { range: '570 km on full charge', topSpeed: '225 km/h', fuelConsumption: '0 L/100km' },
    highlights: ['Full Electric', 'e-AWD', '570 km Range', 'Premium Sedan'],
    description: 'The Genesis Electrified G80 e-AWD is a fully electric premium sedan offering refined design, advanced technology, and the perfect harmony of electric power. Vik Black exterior with Ecru Camel interior creates a luxurious, modern appearance. The all-electric system delivers smooth, silent acceleration — ideal for urban and long-distance driving.',
    category: 'electric',
    featured: false,
  },

  // ─────────────────────────────────────────────
  // NEW 24 CARS (from scraped listings)
  // ─────────────────────────────────────────────
  {
    id: 'bmw-520i-g60',
    brand: 'BMW',
    model: '520i G60 5 Series',
    year: 2025,
    price: 43500,
    tag: 'Pre-Owned',
    mileage: '2,270 km',
    color: 'Black Sapphire Metallic',
    interior: 'Alpine White',
    engine: '2.0L Turbo 4-Cylinder TwinPower',
    power: '208 HP',
    transmission: '8-Speed Automatic',
    fuel: 'Petrol',
    drivetrain: 'RWD',
    image: '/cars/bmw-520i-g60-5-series-2025-god/01.jpg',
    gallery: Array.from({length: 8}, (_, i) => `/cars/bmw-520i-g60-5-series-2025-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 7.5s', topSpeed: '235 km/h', fuelConsumption: '5.7-6.4 L/100km' },
    highlights: ['TwinPower Turbo', 'G60 Generation', 'Business Class', 'Fuel Efficient'],
    description: 'The BMW 520i (G60) is a business-class sedan offering refined design, premium comfort, and advanced technology. Black Sapphire Metallic exterior with Alpine White interior gives the car a classic, distinguished appearance. The turbo petrol engine delivers smooth acceleration and excellent fuel efficiency, while the 8-speed automatic transmission ensures comfortable driving on both city streets and highways. Ideal for daily commutes, business meetings, and long-distance travel.',
    category: 'sedan',
    featured: false,
  },
  {
    id: 'mini-cooper-countryman-se',
    brand: 'MINI',
    model: 'Cooper Countryman SE ALL4',
    year: 2025,
    price: 36000,
    tag: 'Pre-Owned',
    mileage: '9,653 km',
    color: 'Nardo Grey',
    interior: 'Black',
    engine: 'Dual Electric Motors',
    power: '313 HP',
    transmission: 'Single-Speed Automatic',
    fuel: 'Electric',
    drivetrain: 'ALL4 AWD',
    image: '/cars/mini-cooper-countryman-se-all-4-2025-god/01.jpg',
    gallery: Array.from({length: 7}, (_, i) => `/cars/mini-cooper-countryman-se-all-4-2025-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { range: '430-460 km (WLTP)', topSpeed: '180 km/h', fuelConsumption: '0 L/100km' },
    highlights: ['Full Electric', 'ALL4 AWD', '313 HP', '66.5 kWh Battery'],
    description: 'The MINI Cooper Countryman SE ALL4 is a premium compact electric SUV with dual electric motors producing 313 HP and 494 Nm of torque. The 66.5 kWh battery provides a range of up to 460 km on a single charge. ALL4 all-wheel drive system ensures confident handling in any conditions. Nardo Grey exterior with Black interior gives the car a sleek, modern appearance. A perfect combination of fun driving dynamics and zero-emission practicality.',
    category: 'electric',
    featured: false,
  },
  {
    id: 'bmw-i4-edrive-m40',
    brand: 'BMW',
    model: 'i4 eDrive40 M Sport',
    year: 2025,
    price: 47000,
    tag: 'Pre-Owned',
    mileage: '4,171 km',
    color: 'Blue',
    interior: 'Black',
    engine: 'Single Electric Motor (Rear)',
    power: '340 HP',
    transmission: 'Single-Speed Automatic',
    fuel: 'Electric',
    drivetrain: 'RWD',
    image: '/cars/bmw-i4-edrive-m40-2025-god/01.jpg',
    gallery: Array.from({length: 7}, (_, i) => `/cars/bmw-i4-edrive-m40-2025-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { range: '550-590 km (WLTP)', topSpeed: '190 km/h', fuelConsumption: '0 L/100km' },
    highlights: ['Full Electric', 'M Sport', '340 HP', '83.9 kWh Battery'],
    description: 'The BMW i4 eDrive40 M Sport is a premium electric gran coupe delivering 340 HP and 430 Nm from its rear-mounted electric motor. The 83.9 kWh battery provides an impressive range of up to 590 km on a single charge, with fast charging from 10-80% in approximately 30 minutes. Blue exterior with Black interior gives the car a sporty, sophisticated look. Combines BMW driving dynamics with zero-emission technology for the ultimate electric driving experience.',
    category: 'electric',
    featured: false,
  },
  {
    id: 'mercedes-maybach-gls-600-vip',
    brand: 'Mercedes-Maybach',
    model: 'GLS 600 4MATIC 4-Seat VIP',
    year: 2026,
    price: 227000,
    tag: 'New',
    mileage: '0 km',
    color: 'Black',
    interior: 'Brown & Beige Two-Tone',
    engine: '4.0L V8 Twin-Turbo + 48V EQ Boost',
    power: '557 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC AWD',
    image: '/cars/mercedes-maybach-gls-600-4matic-4-seat-vip-2026-god/01.jpg',
    gallery: Array.from({length: 10}, (_, i) => `/cars/mercedes-maybach-gls-600-4matic-4-seat-vip-2026-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 4.9s', topSpeed: '250 km/h', fuelConsumption: '13-14 L/100km' },
    highlights: ['V8 Twin-Turbo', '557 HP', '4-Seat VIP', 'Maybach'],
    description: 'The Mercedes-Maybach GLS 600 4MATIC in the exclusive 4-Seat VIP configuration represents the pinnacle of ultra-luxury SUVs. The 4.0L V8 Twin-Turbo engine with 48V EQ Boost delivers 557 HP and 730 Nm of torque. The VIP four-seat layout provides first-class rear passenger comfort with individual reclining seats. Black exterior with Brown and Beige two-tone interior creates an atmosphere of unparalleled opulence. The ultimate statement of power, prestige, and refinement.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'mercedes-amg-cle-53-cabriolet',
    brand: 'Mercedes-AMG',
    model: 'CLE 53 Cabriolet Limited Edition',
    year: 2026,
    price: 102000,
    tag: 'New',
    mileage: '0 km',
    color: 'Matte Blue',
    interior: 'White',
    engine: '3.0L R6 Turbo + 48V Mild Hybrid',
    power: '449 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC+ AWD',
    image: '/cars/mercedes-amg-cle-53-cabriolet-limitirovannaya-versiya-2026-god/01.jpg',
    gallery: Array.from({length: 10}, (_, i) => `/cars/mercedes-amg-cle-53-cabriolet-limitirovannaya-versiya-2026-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 4.2s', topSpeed: '250 km/h', fuelConsumption: '9-10 L/100km' },
    highlights: ['AMG', 'Cabriolet', 'Limited Edition', '449 HP'],
    description: 'The Mercedes-AMG CLE 53 Cabriolet Limited Edition is a rare, made-to-order sport convertible combining open-top thrills with AMG performance. The 3.0L inline-6 turbo engine with 48V Mild Hybrid produces 449 HP and 560 Nm of torque. Matte Blue exterior with White interior delivers a stunning, head-turning appearance. The retractable soft top lets you enjoy the driving experience in a whole new way. An exclusive limited-production model for those who demand distinction.',
    category: 'coupe',
    featured: false,
  },
  {
    id: 'gle-450-amg-line-2026',
    brand: 'Mercedes-Benz',
    model: 'GLE 450 4MATIC AMG Line',
    year: 2026,
    price: 98000,
    tag: 'New',
    mileage: '5 km',
    color: 'Green',
    interior: 'Black Premium Leather',
    engine: '3.0L Turbo + 48V Mild Hybrid',
    power: '367 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC AWD',
    image: '/cars/gle-450-amg-line-2026-new/01.jpg',
    gallery: Array.from({length: 10}, (_, i) => `/cars/gle-450-amg-line-2026-new/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 5.7s', topSpeed: '250 km/h', fuelConsumption: '9-10 L/100km' },
    highlights: ['AMG Line', '367 HP', 'Panoramic Roof', 'Burmester Audio'],
    description: 'The Mercedes-Benz GLE 450 AMG Line is a factory-fresh premium SUV straight from Korea. The 3.0L turbo engine with Mild Hybrid delivers 367 HP for effortless power. AMG Line package includes sporty exterior styling, AMG 20-inch wheels, and sport interior. Equipped with panoramic roof, MBUX digital cockpit, Burmester premium audio, 360-degree camera, adaptive LED headlights, and electric memory seats. Green exterior with Black premium leather interior creates a distinctive, bold look.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'mercedes-amg-gle-53-coupe',
    brand: 'Mercedes-AMG',
    model: 'GLE 53 4MATIC+ Coupe',
    year: 2026,
    price: 113500,
    tag: 'New',
    mileage: '0 km',
    color: 'Black',
    interior: 'Red & Black Two-Tone',
    engine: '3.0L R6 Turbo + 48V EQ Boost',
    power: '435 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC+ AWD',
    image: '/cars/mercedes-amg-gle-53-4matic-coupe/01.jpg',
    gallery: Array.from({length: 10}, (_, i) => `/cars/mercedes-amg-gle-53-4matic-coupe/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 5.0s', topSpeed: '250 km/h', fuelConsumption: '10-11 L/100km' },
    highlights: ['AMG', '435 HP', 'Coupe SUV', '4MATIC+'],
    description: 'The Mercedes-AMG GLE 53 4MATIC+ Coupe is a sport SUV coupe blending aggressive AMG performance with luxurious comfort. The 3.0L inline-6 turbo with 48V EQ Boost delivers 435 HP and 560 Nm, plus an additional 22 HP from the electric boost system. Black exterior with Red and Black two-tone interior creates a dramatic, performance-oriented cabin. Top speed reaches 250 km/h (or 270 km/h with AMG Driver\'s Package). The perfect fusion of SUV practicality and coupe athleticism.',
    category: 'coupe',
    featured: false,
  },
  {
    id: 'bmw-320i-m-sport',
    brand: 'BMW',
    model: '320i M Sport G20',
    year: 2025,
    price: 38500,
    tag: 'Pre-Owned',
    mileage: '1,900 km',
    color: 'White',
    interior: 'Cognac',
    engine: '2.0L Turbo',
    power: '184 HP',
    transmission: '8-Speed Automatic',
    fuel: 'Petrol',
    drivetrain: 'RWD',
    image: '/cars/bmw-320i-m-sport-g20/01.jpg',
    gallery: Array.from({length: 6}, (_, i) => `/cars/bmw-320i-m-sport-g20/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 7.1s', topSpeed: '235 km/h', fuelConsumption: '6.5-7.5 L/100km' },
    highlights: ['M Sport', '184 HP', 'G20', 'Premium Sedan'],
    description: 'The BMW 320i M Sport (G20) is a premium sedan with sporty M Sport enhancements. White exterior with Cognac interior creates an elegant, refined look. The 2.0L turbo engine delivers smooth power with excellent fuel efficiency. M Sport package includes aerodynamic body kit, M sport steering wheel, sport suspension, and distinctive styling elements. With only 1,900 km, this is practically a brand-new car. Ideal for those seeking BMW driving dynamics at an accessible price point.',
    category: 'sedan',
    featured: false,
  },
  {
    id: 'genesis-g90-long',
    brand: 'Genesis',
    model: 'G90 3.5T AWD Long Wheelbase Night Package',
    year: 2026,
    price: 119500,
    tag: 'New',
    mileage: '200 km',
    color: 'Black',
    interior: 'Black (Night Package)',
    engine: '3.5L V6 Twin-Turbo + Electric Supercharger',
    power: '415 HP',
    transmission: '8-Speed Automatic',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: 'AWD',
    image: '/cars/genesis-g90-3-5t-long-night-paket-2026-god/01.jpg',
    gallery: Array.from({length: 7}, (_, i) => `/cars/genesis-g90-3-5t-long-night-paket-2026-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 5.2s', topSpeed: '250 km/h', fuelConsumption: '10-12 L/100km' },
    highlights: ['Long Wheelbase', 'Night Package', 'V6 Twin-Turbo', '415 HP'],
    description: 'The Genesis G90 3.5T AWD Long Wheelbase with Night Package is an ultra-luxury sedan featuring the extended wheelbase for maximum rear passenger comfort. The 3.5L V6 Twin-Turbo engine with electric supercharger and 48V Mild Hybrid system produces 415 HP and 549 Nm. All-black Night Package gives the car a stealthy, commanding presence. Any configuration can be custom-ordered to your exact specifications. A flagship sedan rivaling the best from Germany at a compelling value.',
    category: 'sedan',
    featured: false,
  },
  {
    id: 'lamborghini-huracan-sto',
    brand: 'Lamborghini',
    model: 'Huracan STO LP640-2',
    year: 2023,
    price: 302000,
    tag: 'Pre-Owned',
    mileage: '500 km',
    color: 'Verde (Dark Racing Green)',
    interior: 'Black Alcantara with Arancio Accents',
    engine: '5.2L V10 Naturally Aspirated',
    power: '640 HP',
    transmission: '7-Speed Dual-Clutch (LDF)',
    fuel: 'Petrol',
    drivetrain: 'RWD',
    image: '/cars/lamborghini-huracn-sto-lp640-2/01.jpg',
    gallery: Array.from({length: 9}, (_, i) => `/cars/lamborghini-huracn-sto-lp640-2/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 3.0s', topSpeed: '310 km/h', fuelConsumption: '14-16 L/100km' },
    highlights: ['V10 Naturally Aspirated', '640 HP', 'STO', 'Track-Ready'],
    description: 'The Lamborghini Huracan STO (Super Trofeo Omologata) LP640-2 is not an ordinary Huracan. This model is derived directly from Lamborghini\'s Super Trofeo and GT3 race cars, featuring carbon body panels, maximum aerodynamics, lightweight construction, and a track-tuned chassis. The naturally aspirated 5.2L V10 produces 640 HP channeled through the rear wheels for a pure, adrenaline-filled driving experience. Verde dark racing green exterior with Black Alcantara and Arancio accents. With only 500 km, this is an essentially new collector-grade supercar.',
    category: 'sports',
    featured: false,
  },
  {
    id: 'porsche-panamera-e-hybrid',
    brand: 'Porsche',
    model: 'Panamera 2.9 E-Hybrid AWD',
    year: 2025,
    price: 142000,
    tag: 'Pre-Owned',
    mileage: '5,400 km',
    color: 'Jet Black Metallic',
    interior: 'Black & Saddle Brown',
    engine: '2.9L V6 Turbo + Electric Motor (PHEV)',
    power: '462 HP (combined)',
    transmission: 'PDK Automatic',
    fuel: 'Plug-in Hybrid',
    drivetrain: 'AWD',
    image: '/cars/porsche-panamera-e-hybrid-2-9-972-awd/01.jpg',
    gallery: Array.from({length: 5}, (_, i) => `/cars/porsche-panamera-e-hybrid-2-9-972-awd/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 4.1s', topSpeed: '280 km/h', fuelConsumption: '3.1-3.8 L/100km (WLTP)' },
    highlights: ['Plug-in Hybrid', 'V6 Turbo', '462 HP', 'Porsche PDK'],
    description: 'The Porsche Panamera 2.9 AWD E-Hybrid combines sports car dynamics with plug-in hybrid technology. The 2.9L V6 turbo paired with an electric motor delivers combined output for breathtaking performance: 0-100 km/h in just 4.1 seconds and a top speed of 280 km/h. In hybrid mode, fuel consumption drops to as low as 3.1 L/100km. Jet Black Metallic exterior with Black and Saddle Brown interior creates a sophisticated, premium ambiance. A grand touring sedan that delivers Porsche thrills with everyday efficiency.',
    category: 'sedan',
    featured: false,
  },
  {
    id: 'gle-450-4matic-amg',
    brand: 'Mercedes-Benz',
    model: 'GLE 450 4MATIC AMG Line',
    year: 2026,
    price: 95000,
    tag: 'New',
    mileage: '10 km',
    color: 'Polar White',
    interior: 'Black Premium Leather',
    engine: '3.0L Turbo + 48V Mild Hybrid',
    power: '367 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC AWD',
    image: '/cars/gle-450-4m-amg-line-2026/01.jpg',
    gallery: Array.from({length: 9}, (_, i) => `/cars/gle-450-4m-amg-line-2026/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 5.7s', topSpeed: '250 km/h', fuelConsumption: '9-10 L/100km' },
    highlights: ['AMG Line', '367 HP', 'AMG 20" Wheels', '360 Camera'],
    description: 'The Mercedes-Benz GLE 450 4MATIC AMG Line in Polar White combines modern design, maximum comfort, and advanced technology in one vehicle. Imported directly from Korean authorized dealers, factory-fresh with just 10 km on the odometer. The 3.0L turbo with Mild Hybrid delivers 367 HP through the 4MATIC AWD system. Equipped with panoramic roof, MBUX digital cockpit, Burmester premium audio, 360-degree camera, adaptive LED headlights, and electric memory seats. A premium SUV offering power, reliability, and luxury.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'bmw-m4-cs',
    brand: 'BMW',
    model: 'M4 CS xDrive G82',
    year: 2025,
    price: 131000,
    tag: 'Pre-Owned',
    mileage: '5,555 km',
    color: 'Frozen Green',
    interior: 'Sport M Interior',
    engine: '3.0L S58 Twin-Turbo R6',
    power: '550 HP',
    transmission: '8-Speed M Steptronic',
    fuel: 'Petrol',
    drivetrain: 'M xDrive AWD',
    image: '/cars/bmw-m4-cs-xdrive-g82-2025-god/01.jpg',
    gallery: Array.from({length: 6}, (_, i) => `/cars/bmw-m4-cs-xdrive-g82-2025-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 3.4s', topSpeed: '302 km/h', fuelConsumption: '10-12 L/100km' },
    highlights: ['M4 CS', '550 HP', 'Carbon Roof', 'xDrive AWD'],
    description: 'The BMW M4 CS xDrive (G82) is the pinnacle of BMW M performance coupes. The legendary 3.0L S58 twin-turbo inline-6 produces 550 HP and 650 Nm, launching from 0-100 km/h in just 3.4 seconds with a top speed of 302 km/h (M Driver\'s Package). Frozen Green exterior with M Sport interior creates a striking, exclusive appearance. Features include carbon fiber roof for reduced weight, Active M Differential, and M xDrive all-wheel drive. A track-capable weapon that remains comfortable for daily driving.',
    category: 'coupe',
    featured: false,
  },
  {
    id: 'bmw-m5-g90',
    brand: 'BMW',
    model: 'M5 G90 PHEV',
    year: 2025,
    price: 129000,
    tag: 'Pre-Owned',
    mileage: '5,500 km',
    color: 'Black',
    interior: 'Black',
    engine: '4.4L V8 Twin-Turbo + Electric Motor (PHEV)',
    power: '727 HP',
    transmission: '8-Speed M Steptronic',
    fuel: 'Plug-in Hybrid',
    drivetrain: 'M xDrive AWD',
    image: '/cars/bmw-m5-g90-2025-god/01.jpg',
    gallery: Array.from({length: 7}, (_, i) => `/cars/bmw-m5-g90-2025-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 3.5s', topSpeed: '305 km/h', fuelConsumption: '1.7 L/100km (WLTP combined)' },
    highlights: ['V8 Twin-Turbo PHEV', '727 HP', '1,000 Nm', 'Electric Range ~65 km'],
    description: 'The BMW M5 (G90) is the most powerful M5 ever built. The 4.4L V8 Twin-Turbo M TwinPower engine combined with an electric motor delivers a staggering 727 HP and 1,000 Nm of torque through the M xDrive AWD system. The plug-in hybrid battery provides approximately 60-70 km of pure electric range. 0-100 km/h takes just 3.5 seconds, delivering supercar-level acceleration in a practical sport sedan. Black on Black creates a stealthy, commanding presence. The ultimate high-performance business sedan.',
    category: 'sedan',
    featured: false,
  },
  {
    id: 'mercedes-maybach-gls600-night',
    brand: 'Mercedes-Maybach',
    model: 'GLS 600 Night Series',
    year: 2026,
    price: 252000,
    tag: 'New',
    mileage: '0 km',
    color: 'Black',
    interior: 'Maybach Exclusive Nappa Leather Black',
    engine: '4.0L V8 Biturbo + 48V EQ Boost',
    power: '557 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC AWD',
    image: '/cars/mercedes-maybach-gls600-night-series-2026-god/01.jpg',
    gallery: Array.from({length: 6}, (_, i) => `/cars/mercedes-maybach-gls600-night-series-2026-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 4.9s', topSpeed: '250 km/h', fuelConsumption: '13-14 L/100km' },
    highlights: ['Night Series', 'V8 Biturbo', '557 HP', 'E-Active Body Control'],
    description: 'The Mercedes-Maybach GLS 600 Night Series is the darkest expression of the ultra-luxury Maybach SUV. The exclusive Night Series package features blacked-out accents for a bold, commanding design language. The 4.0L V8 Biturbo with 48V EQ Boost Mild Hybrid delivers 557 HP and 730 Nm. Equipped with E-Active Body Control suspension, Maybach Exclusive Nappa leather interior, and the highest level of comfort and technology. Imported directly from authorized Korean dealers. The ultimate luxury SUV for those who prefer the dark side of opulence.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'lamborghini-urus-se',
    brand: 'Lamborghini',
    model: 'Urus SE Special Edition',
    year: 2025,
    price: 334500,
    tag: 'New',
    mileage: '100 km',
    color: 'Black Matte',
    interior: 'Black',
    engine: '4.0L V8 Twin-Turbo + Electric Motor (PHEV)',
    power: '800 HP',
    transmission: '8-Speed Automatic',
    fuel: 'Plug-in Hybrid',
    drivetrain: 'AWD',
    image: '/cars/lamborghini-urus-special-edition-2025-god/01.jpg',
    gallery: Array.from({length: 10}, (_, i) => `/cars/lamborghini-urus-special-edition-2025-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 3.4s', topSpeed: '312 km/h', fuelConsumption: '6-8 L/100km (WLTP combined)' },
    highlights: ['800 HP', 'Plug-in Hybrid', 'Special Edition', 'Supercar SUV'],
    description: 'The Lamborghini Urus SE is the most powerful Urus ever made, combining a 4.0L V8 Twin-Turbo engine with an electric motor for a combined 800 HP and approximately 950 Nm of torque. The plug-in hybrid system provides around 60 km of pure electric range via its 25.9 kWh battery, with the ability to drive in full electric, petrol, or hybrid modes. Black Matte exterior with Black interior delivers an ultra-aggressive, stealth appearance. With only 100 km on the odometer, this is essentially a brand-new supercar SUV. Supercar-level acceleration with the practicality of an SUV.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'mercedes-gls-450-night',
    brand: 'Mercedes-Benz',
    model: 'GLS 450 4MATIC Night Package',
    year: 2026,
    price: 121000,
    tag: 'New',
    mileage: '0 km',
    color: 'Black',
    interior: 'Black',
    engine: '3.0L R6 Turbo + 48V EQ Boost',
    power: '375 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC AWD',
    image: '/cars/mercedes-benz-gls-450-4matic-3-0l-nochnoy-paket-2026-god/01.jpg',
    gallery: Array.from({length: 5}, (_, i) => `/cars/mercedes-benz-gls-450-4matic-3-0l-nochnoy-paket-2026-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 5.9s', topSpeed: '250 km/h', fuelConsumption: '10-11 L/100km' },
    highlights: ['Night Package', '375 HP', 'Full-Size SUV', '4MATIC'],
    description: 'The Mercedes-Benz GLS 450 4MATIC with Night Package is a full-size premium SUV combining commanding presence with refined luxury. The 3.0L inline-6 turbo with 48V EQ Boost Mild Hybrid system delivers 375 HP and approximately 500 Nm, plus an additional 20-22 HP from the electric boost. Night Package adds blacked-out design elements for a bold, aggressive look. Black exterior with Black interior creates a fully monochrome, stealth appearance. Imported directly from Korean authorized dealers with zero kilometers. The full-size luxury SUV for families and executives who demand space, power, and prestige.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'mercedes-e300-amg-grey',
    brand: 'Mercedes-Benz',
    model: 'E 300 AMG Line',
    year: 2026,
    price: 67500,
    tag: 'New',
    mileage: '0 km',
    color: 'White',
    interior: 'Beige',
    engine: '2.0L Turbo + 48V Mild Hybrid',
    power: '258 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: 'RWD',
    image: '/cars/mercedes-e300-amg-line-grey/01.jpg',
    gallery: Array.from({length: 7}, (_, i) => `/cars/mercedes-e300-amg-line-grey/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 6.1s', topSpeed: '250 km/h', fuelConsumption: '7-8 L/100km' },
    highlights: ['AMG Line', '258 HP', 'E-Class 2026', 'Mild Hybrid'],
    description: 'The Mercedes-Benz E 300 AMG Line is the ideal fusion of business-class comfort and sporty design. The AMG Line exterior and interior design package gives the car a modern, dynamic appearance. White exterior with Beige interior emphasizes refinement and premium taste. The 2.0L turbo engine with 48V Mild Hybrid delivers 258 HP with smooth performance and excellent fuel efficiency. Modern technology, smooth ride, and high comfort make this the perfect choice for daily use, business meetings, and long journeys.',
    category: 'sedan',
    featured: false,
  },
  {
    id: 'mercedes-e300-amg-white',
    brand: 'Mercedes-Benz',
    model: 'E 300 AMG Line',
    year: 2026,
    price: 67500,
    tag: 'New',
    mileage: '0 km',
    color: 'Black',
    interior: 'Black',
    engine: '2.0L Turbo + 48V Mild Hybrid',
    power: '258 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: 'RWD',
    image: '/cars/mercedes-e300-amg-line-white/01.jpg',
    gallery: Array.from({length: 4}, (_, i) => `/cars/mercedes-e300-amg-line-white/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 6.1s', topSpeed: '250 km/h', fuelConsumption: '7-8 L/100km' },
    highlights: ['AMG Line', '258 HP', 'E-Class 2026', 'All-Black'],
    description: 'The Mercedes-Benz E 300 AMG Line in all-Black is the perfect blend of business-class comfort and sporty design. The AMG Line exterior and interior package gives the car an aggressive, modern look, with Black bodywork and Black interior emphasizing premium style. Mild Hybrid technology reduces fuel consumption and ensures smoother acceleration. An ideal choice for daily commuting, business, and long-distance travel.',
    category: 'sedan',
    featured: false,
  },
  {
    id: 'mercedes-glc-300-coupe',
    brand: 'Mercedes-Benz',
    model: 'GLC 300 4MATIC Coupe',
    year: 2026,
    price: 71000,
    tag: 'New',
    mileage: '0 km',
    color: 'White',
    interior: 'Brown',
    engine: '2.0L Turbo + 48V Mild Hybrid',
    power: '258 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC AWD',
    image: '/cars/mercedes-benz-glc-300-4matic-coupe-2026-god/01.jpg',
    gallery: Array.from({length: 7}, (_, i) => `/cars/mercedes-benz-glc-300-4matic-coupe-2026-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 6.4s', topSpeed: '240 km/h', fuelConsumption: '7-8 L/100km' },
    highlights: ['Coupe Design', '258 HP', '4MATIC', 'Mild Hybrid'],
    description: 'The Mercedes-Benz GLC 300 4MATIC Coupe combines sporty coupe styling with premium SUV comfort and modern technology. White exterior with Brown interior delivers a refined, contemporary look. The 2.0L turbo with 48V Mild Hybrid reduces fuel consumption and ensures smooth acceleration. 4MATIC all-wheel drive system provides reliable handling in any road conditions. Ideal for those who value both stylish design and everyday practicality.',
    category: 'coupe',
    featured: false,
  },
  {
    id: 'mercedes-gle-450-coupe-night',
    brand: 'Mercedes-Benz',
    model: 'GLE 450 4MATIC Coupe Night Edition',
    year: 2026,
    price: 104000,
    tag: 'New',
    mileage: '0 km',
    color: 'Black',
    interior: 'Black',
    engine: '3.0L R6 Turbo + 48V Mild Hybrid',
    power: '381 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC AWD',
    image: '/cars/mercedes-benz-gle-450-4matic-coupe-night-edition-2026-god/01.jpg',
    gallery: Array.from({length: 8}, (_, i) => `/cars/mercedes-benz-gle-450-4matic-coupe-night-edition-2026-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 5.5s', topSpeed: '250 km/h', fuelConsumption: '9-10 L/100km' },
    highlights: ['Night Edition', '381 HP', 'Coupe SUV', '4MATIC'],
    description: 'The Mercedes-Benz GLE 450 4MATIC Coupe Night Edition is a perfect fusion of sporty design, luxury, and modern technology. The Night Edition blacked-out design elements give the car an aggressive, exclusive appearance. All-Black exterior and interior emphasize premium style. The 3.0L inline-6 turbo with 48V Mild Hybrid provides 381 HP with smooth dynamics and improved fuel efficiency. 4MATIC all-wheel drive ensures reliable control in any road conditions. A sporty yet comfortable premium SUV coupe for those who appreciate distinctive character.',
    category: 'coupe',
    featured: false,
  },
  {
    id: 'mercedes-amg-gls-63',
    brand: 'Mercedes-AMG',
    model: 'GLS 63 4MATIC+',
    year: 2026,
    price: 162000,
    tag: 'New',
    mileage: '0 km',
    color: 'Black',
    interior: 'Black',
    engine: '4.0L V8 Biturbo + 48V Mild Hybrid',
    power: '612 HP',
    transmission: '9G-TRONIC AMG',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC+ AWD',
    image: '/cars/mercedes-amg-gls-63-4matic-2026-god/01.jpg',
    gallery: Array.from({length: 8}, (_, i) => `/cars/mercedes-amg-gls-63-4matic-2026-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 4.2s', topSpeed: '280 km/h', fuelConsumption: '13-14 L/100km' },
    highlights: ['AMG V8 Biturbo', '612 HP', '7-Seat', '4MATIC+'],
    description: 'The Mercedes-AMG GLS 63 4MATIC+ is a premium SUV that unites luxury, power, and sport character in a 7-seat package. The handcrafted AMG 4.0L V8 Biturbo with 48V Mild Hybrid delivers 612 HP for exhilarating acceleration and driving pleasure. 4MATIC+ all-wheel drive ensures maximum control and stability in any conditions. Black exterior with Black interior creates a serious, aggressive look in the full AMG spirit. Imported directly from Korean authorized dealers. The most powerful GLS for those who refuse to compromise.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'mercedes-amg-g63',
    brand: 'Mercedes-AMG',
    model: 'G 63',
    year: 2026,
    price: 207000,
    tag: 'New',
    mileage: '0 km',
    color: 'Black',
    interior: 'Beige',
    engine: '4.0L V8 Biturbo + 48V Mild Hybrid',
    power: '585 HP',
    transmission: '9G-TRONIC',
    fuel: 'Petrol + Mild Hybrid',
    drivetrain: '4MATIC AWD',
    image: '/cars/mercedes-amg-g63/01.jpg',
    gallery: Array.from({length: 7}, (_, i) => `/cars/mercedes-amg-g63/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { acceleration: '0-100 km/h in 4.4s', topSpeed: '220 km/h', fuelConsumption: '14-15 L/100km' },
    highlights: ['AMG V8 Biturbo', '585 HP', 'G-Class', 'Iconic Design'],
    description: 'The Mercedes-AMG G 63 is the most powerful and luxurious version of the legendary G-Class. The handcrafted AMG 4.0L V8 Biturbo with 48V Mild Hybrid delivers 585 HP for aggressive dynamics and maximum driving pleasure. Body-on-frame construction with permanent 4MATIC all-wheel drive ensures unstoppable capability on any terrain. Black exterior with Beige interior gives the car a classic, distinguished, and premium appearance. Imported from an authorized Korean dealer. A symbol of power, luxury, and prestige.',
    category: 'suv',
    featured: false,
  },
  {
    id: 'porsche-macan-ev',
    brand: 'Porsche',
    model: 'Macan EV 4',
    year: 2025,
    price: 89000,
    tag: 'Pre-Owned',
    mileage: '3,521 km',
    color: 'White',
    interior: 'Premium Interior',
    engine: 'Dual Electric Motors',
    power: '408 HP',
    transmission: 'Single-Speed Automatic',
    fuel: 'Electric',
    drivetrain: 'AWD',
    image: '/cars/porsche-macan-ev-4-2025-god/01.jpg',
    gallery: Array.from({length: 7}, (_, i) => `/cars/porsche-macan-ev-4-2025-god/${String(i+1).padStart(2,'0')}.jpg`),
    specs: { range: '550-600 km (WLTP)', topSpeed: '220 km/h', fuelConsumption: '0 L/100km' },
    highlights: ['Full Electric', '408 HP', '800V Architecture', 'AWD'],
    description: 'The Porsche Macan EV 4 is a premium all-electric SUV with dual electric motors delivering 408 HP and approximately 650 Nm of torque through the AWD system. Built on the industry-leading 800V architecture, the 100 kWh battery provides a range of up to 600 km on a single charge, with ultra-fast charging from 10-80% in just 21 minutes. White exterior with premium interior creates a clean, modern appearance. With only 3,521 km, this is practically a new vehicle. The perfect combination of Porsche driving dynamics and zero-emission technology.',
    category: 'electric',
    featured: false,
  },
];

// Extract unique brand names from inventory
export const brands = [...new Set(inventory.map(car => car.brand))];
